Organization:
    type: object
    config:
        description: "An OroCommerce Organization"
        fields:
            id:
                type: "String!"
                description: "The id of the Organization."
            name:
                type: "String"
                description: "The name of the Organization."
